### ISSUE TITLE
ares question

### ISSUE THREAD

**Issue by ghost** [flathub/dev.ares.ares#13] opened 2022-01-30 16:52 UTC
For an emulator called ares it gives me an error as " Gtk-Message: 21:59:20.577: ".Failed to load module “canberra-gtk-module”. How can I solve it? The bug is precisely this:Gtk-Message: 21:59:20.577: Failed to load module “canberra-gtk-module”.

**Comment by hfiguiere** [comment] 2022-01-30 16:55
this is not an error, at least not one that matter at all.

**Comment by Stusichino** [comment] 2022-01-30 17:00
But the software does not start.

**Comment by Stusichino** [comment] 2022-01-30 17:02
But the software does not start. And when I started it from the command line, not only did it not start, but the following message would appear.

**Comment by hfiguiere** [comment] 2022-01-30 17:05
correlation is not causation.

**Comment by Stusichino** [comment] 2022-01-30 17:10
so what does it mean? is it the fault of the repository or my pc or something else?

**Comment by ghisvail** [comment] 2022-01-30 17:45
Please give us the __full__ output of `flatpak run dev.ares.ares`.

**Comment by hfiguiere** [comment] 2022-01-30 18:01
the problem is that when the application crash there is not even a message about it. (it's flatpak) so it looks like these message that display virtually in every other app are the reason.

(just setting the level of expectation here)

**Comment by hfiguiere** [comment] 2022-01-30 18:22
one way to see where it crash, and it require to install the sdk org.freedesktop.Sdk//21.08
(it's big)

```
$ flatpak run --devel --command=sh dev.ares.ares
$ gdb ares
gdb> r
```

Then when it crashes:
```
gdb> where
```

**Comment by Stusichino** [comment] 2022-01-30 21:03
thanks

**Comment by Stusichino** [comment] 2022-01-31 13:27
#0  0x0000555555abb47e in  ()
#1  0x0000555555afe9be in  ()
#2  0x000055555567c98a in nall::main(nall::Arguments) ()
#3  0x0000555555677fba in nall::main(int, char**) ()
#4  0x00007ffff641eb90 in __libc_start_main () at /usr/lib/x86_64-linux-gnu/libc.so.6
#5  0x00005555556df54e in _start ()

**Comment by Stusichino** [comment] 2022-02-03 16:02
how do I install the freedesktop.Platform.GL.default//21.08?

**Comment by ghisvail** [comment] 2022-02-03 17:30
https://docs.flatpak.org/en/latest/using-flatpak.html

**Comment by Stusichino** [comment] 2022-02-04 17:09
And org.freedesktop.Platform.openh264 2.0?

**Comment by Stusichino** [comment] 2022-02-04 17:28
the bug is:While downloading http://ciscobinary.openh264.org/libopenh264-2.1.1-linux64.6.so.bz2: Could not connect:the network is not reachable

**Comment by Stusichino** [comment] 2022-02-04 17:30
While downloading http://ciscobinary.openh264.org/libopenh264-2.1.1-linux64.6.so.bz2: Could not connect:the network is not reachable.
How i do?

**Comment by ghisvail** [comment] 2024-04-01 09:49
Closing, nothing actionable.

**Closed by ghisvail** 2024-04-01 09:49 UTC
Labels: invalid
